// Mocks generated by Mockito 5.4.4 from annotations
// in beercules/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:beercules/ui/screens/home/home_view.dart' as _i2;
import 'package:beercules/ui/screens/home/services/home_navigation_service.dart'
    as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeController extends _i1.Mock implements _i2.HomeController {
  MockHomeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void goToCustomizeView() => super.noSuchMethod(
        Invocation.method(
          #goToCustomizeView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goToGameView() => super.noSuchMethod(
        Invocation.method(
          #goToGameView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void goToRulesView() => super.noSuchMethod(
        Invocation.method(
          #goToRulesView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showModalLegalNotice() => super.noSuchMethod(
        Invocation.method(
          #showModalLegalNotice,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HomeNavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeNavigationService extends _i1.Mock
    implements _i3.HomeNavigationService {
  MockHomeNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void push(String? uri) => super.noSuchMethod(
        Invocation.method(
          #push,
          [uri],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.TaskEither<Object, _i4.Option<T>> showModal<T>(_i5.Widget? widget) =>
      (super.noSuchMethod(
        Invocation.method(
          #showModal,
          [widget],
        ),
        returnValue: _i6.dummyValue<_i4.TaskEither<Object, _i4.Option<T>>>(
          this,
          Invocation.method(
            #showModal,
            [widget],
          ),
        ),
      ) as _i4.TaskEither<Object, _i4.Option<T>>);
}
