
stages:
  - build
  - deploy

build_website:
  image: cirrusci/flutter:latest
  stage: build
  environment: Production
  only:
    - main
  script:
    - flutter clean
    - flutter pub get
    - flutter build web --release
  artifacts:
    paths:
      - build/web

deploy_website:
  image: node:latest
  stage: deploy
  environment: Production
  only:
    - main
  script:
    - npm install -g firebase-tools
    - echo $FIREBASE_DEPLOY_KEY > "$HOME"/gcloud.json
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --only hosting --token $FIREBASE_TOKEN