name: beercules
description: Beercules

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+26

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  beamer: ^1.0.0
  easy_localization: ^3.0.0
  flutter_riverpod: ^2.0.2
  lottie: ^1.3.0
  riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  auto_size_text: ^3.0.0
  flutter_html: ^2.2.1
  flutter_swipable:
    git:
      url: https://github.com/Akhil111993/swipable_fix_overflow
      ref: master
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.1.5
  responsive_framework: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/instructions/
    - assets/lotties/
    - assets/legal/
    - assets/mockups/
    - assets/backgrounds/
