name: beercules
description: Beercules
publish_to: 'none'
version: 5.0.0
build: 32

environment:
  flutter: ">=3.13.4 <4.0.0"
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.0.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.5.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.0.2
  flutter_svg: ^2.0.10+1
  flutter_swipable:
    git:
      url: https://github.com/Akhil111993/swipable_fix_overflow
      ref: master
  fpdart: ^1.1.0
  freezed_annotation: ^2.1.0
  go_router: ^13.2.0
  google_mobile_ads: ^4.0.0
  lottie: ^2.6.0
  mockito: ^5.4.4
  responsive_framework: ^1.1.1
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.5
  user_messaging_platform: ^1.3.0

dev_dependencies:
  austerity: ^1.1.0
  build_runner: ^2.4.4
  flutter_gen: ^5.5.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.7
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  go_router_builder: ^2.4.1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.11



flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/instructions/
    - assets/lotties/
    - assets/legal/
    - assets/mockups/
    - assets/backgrounds/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    lottie: true


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2196f3"
  adaptive_icon_monochrome: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  background_color_ios: "#2196f3"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "##2196f3"
    theme_color: "#2196f3"
flutter_native_splash:
  color: "#2196f3"
  image: "assets/images/logo.png"
  android_12:
    color: "#2196f3"
    icon_background_color: "#2196f3"
    image_dark: "assets/images/logo.png"
    color_dark: "#2196f3"
    icon_background_color_dark: "#2196f3"

  android_gravity: top
  