name: beercules
description: Beercules
publish_to: 'none'
version: 4.0.0
build: 30

environment:
  flutter: ">=3.13.4 <4.0.0"
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.0.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.0.2
  flutter_svg: ^2.0.10+1
  flutter_swipable:
    git:
      url: https://github.com/Akhil111993/swipable_fix_overflow
      ref: master
  fpdart: ^1.1.0
  freezed_annotation: ^2.1.0
  go_router: ^13.2.0
  lottie: ^2.6.0
  responsive_framework: ^1.1.1
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.1.5

dev_dependencies:
  austerity: ^1.1.0
  build_runner: ^2.4.4
  flutter_gen: ^5.3.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/instructions/
    - assets/lotties/
    - assets/legal/
    - assets/mockups/
    - assets/backgrounds/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
