name: beercules_flutter
description: Beercules

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  beamer: ^1.0.0
  easy_localization: ^3.0.0
  flutter_riverpod: ^1.0.2
  riverpod: ^1.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
