name: beercules
description: Beercules

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.0+26

environment:
  flutter: ">=3.13.4 <4.0.0"
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  beamer: ^1.0.0
  easy_localization: ^3.0.0
  flutter_riverpod: ^2.0.2
  go_router: ^12.1.1
  lottie: ^2.6.0
  fpdart: ^1.1.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_swipable:
    git:
      url: https://github.com/Akhil111993/swipable_fix_overflow
      ref: master
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.1.5
  responsive_framework: ^1.1.1
  collection: ^1.17.2

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.1.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/instructions/
    - assets/lotties/
    - assets/legal/
    - assets/mockups/
    - assets/backgrounds/
