# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Archive production IPA file"
  lane :archive_prod do
    create_keychain(
      name: "fastlane_keychain",
      password: "temp",
      unlock: true,
      timeout: 3600
    )
    match(
      type: "appstore",
      readonly: true,
      api_key_path: '/Users/julian/Downloads/AuthKey_AV63RSP74P.p8',
      keychain_name: "fastlane_keychain",
      app_identifier: [
        "com.zellnapps.beercules",
      ]
    )
    gym(scheme: "Runner")
    delete_keychain(
      name: "fastlane_keychain"
    )
  end

  desc "Deploy production to TestFlight"
    lane :deploy_prod do
      upload_to_testflight(
        api_key_path: '/Users/julian/Downloads/AuthKey_AV63RSP74P.p8',
        notify_external_testers: false,
        skip_waiting_for_build_processing: true
      )
    end
end
